# -*- mode: snippet; require-final-newline: nil -*-
# name: makefile
# key: makefile
# --
# Macro
RM      = rm -f
TARGETS = 

# Rules
.PHONY: all clean

all: $(TARGETS)

clean:
        $(RM) -v $(TARGETS)
        $(RM) *~
